version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-losekann
    working_dir: /var/www/app/
    environment:
      - VIRTUAL_HOST=marcoslosekann.com.br
    restart: "always"
networks:
  default:
    name: nginxproxy_default
